### ISSUE TITLE
Move the java wrapper into the app?

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-android#175]
And switch to using HTTP client like [Retrofit](http://square.github.io/retrofit/) to turn the API endpoints into Java interface

**Comment by marcoherbst** [comment]
Could this be the right approach ?
https://github.com/swagger-api/swagger-codegen

M

**Comment by marcoherbst** [comment]
(It's all swagger 2.0 ... we're on 1.x ... but we will move to 2.0 soon enough )

**Comment by liutingdu** [comment]
It looks like building the wrapper in a different way, the app still doesn't have access to code in the wrapper. The only benefit is saving the time writing the wrapper but it complicates everything else (maintaining, testing, troubleshooting and so on)
