### ISSUE TITLE
There is no way to add preset if a camera has zero preset e.g. Waxie Dargle Cam

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-android#179]

**Comment by marcoherbst** [comment]
Just in case this issue is misconstrued ... the waxie dargle ptz seems to have some other problem.

I think it might be because we're using it via virtual host (ask @faisal2472 ) and that does not allow PTZ control ... but I'm not sure.

Your ticket might be correct, just double check.

**Comment by Zulqarnain-Mustafa** [comment]
PTZ controls are shown for Waxie Dargle Cam, but when we tap on preset list icon it shows nothing, meaning not able to add preset, in general, if a camera has zero presets no list will be load and no add preset button will be available, i will double check that.

**Comment by marcoherbst** [comment]
Good stuff. 2 things:
1. Faisal is upgrading this firmware right now, we had some issues doing that previously but Hikvision have given him some advice to do it in smaller increments.
2. This camera is working over Virtual Host ... which is different to working directly with the camera. Faisal can explain if you need.

Summary: dont worry about this camera misbehaving ... check first if it works on dash ... if it does, ok, its and Android issue. But, it probably doesn't.

**Comment by Zulqarnain-Mustafa** [comment]
Yes it is an Android issue that is why it is here. It needs to fix.

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst need a camera where i have zero presets. I have asked @faisal2472 but he need permission to do that.

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst  we do not have any camera with permission to delete its Presets, please provide a camera where we can do testing with presets.
