### ISSUE TITLE
Evercam is not stable in Android 4.4

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-android#180]
Evercam crashes most of the time because of the memory issue on Android 4.2 and 4.4, here is the screenshot from google developer console:
![screen shot 2016-07-11 at 12 11 05 pm](https://cloud.githubusercontent.com/assets/8174314/16722624/4a9fb0b6-4761-11e6-9e53-a5d0ce67dc12.png)

**Comment by marcoherbst** [comment]
Good stuff

@liutingdu , does anything obvious jump out at you here? It's failing when I open a camera on Android KitKat. Suggestions where we should look?

**Comment by liutingdu** [comment]
@marcoherbst I've never seen this before. Is it a very high resolution video? OutOfMemory usually happens on low memory devices so it might not be strictly  related to Kitkat.

I see quite a lot [discussions around ExoPlayer+OutOfMemoryError](https://www.google.ie/?ion=1&espv=2#q=exoplayer%20outofmemory%20error), I think the only way to troubleshoot it is to look through those discussions and try the suggested solutions (there are people suggesting adding `largeHeap` but not sure it will work or not) 💃

**Comment by marcoherbst** [comment]
@liutingdu you're the best.

@Zulqarnain-Mustafa I just tested this on a jpeg only camera (no exoplayer) and also got a crash. (I can't open any camera on my device).

This is the phone:
http://www.gsmarena.com/htc_desire_510-6608.php

**Comment by Zulqarnain-Mustafa** [comment]
@liutingdu you might be right because @yasir also reported that it happens on devices with low memory with Android 4.4 but you may be right that it is not because of KitKat.
@marcoherbst we need to handle the memory on low memory devices, or there must be a check to flush the memory or i think there is garbage collection in Jave to free the memory for unused objects in application. In iOS we receive warning when there is memory issue,  there must be a way in Android to handle that as well.
