### ISSUE TITLE
Add validations for email on sign up.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-android#193]
An irregular email can be added,on sign up and no error will be given.In fact, it will take us to the index page.This should not happen.

**Comment by marcoherbst** [comment]
1. @muneeb2542 there is not enough info in this ticket. 
2. @Zulqarnain-Mustafa feel free to recommend that this is solved @ server side, not client. You can decide what you think is best for the project, bearing in mind that we have wasting time on this task for about 2 years without success.
