### ISSUE TITLE
Show proper string in error messages from media

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-android#194]
![img_1412](https://cloud.githubusercontent.com/assets/8174314/18124697/cb2125f0-6f8c-11e6-9918-bee86d9a0fcc.JPG)

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst it is fixed in Edit camera screen but need to be implemented in more places where we are using POST or PATCH request.

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa Does this change applies to error responses for all the API endpoints? If so, you can just change it from [here](https://github.com/evercam/evercam.java/blob/master/src/main/java/io/evercam/ErrorResponse.java#L29) and call it from the POST/PATCH requests

**Comment by Zulqarnain-Mustafa** [comment]
@liutingdu It is done as you suggested.

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa Why did you stop pushing code to Github? 😆

**Comment by marcoherbst** [comment]
Good question @liutingdu  !!! :)

**Comment by Zulqarnain-Mustafa** [comment]
@liutingdu Here is my pull request:
https://github.com/evercam/evercam-android/pull/197
Please review my code and if you find it suitable to merge, let me know and i will merge it.
I have forked the evercam-android because i am new to android,so do not want to mess up the things. :)
