### ISSUE TITLE
Snapshot url does not fill up on edit camera screen when vendor and model is unknown

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-android#216]
![screenshot_1476877086](https://cloud.githubusercontent.com/assets/8174314/19517441/9e8bcbf8-961a-11e6-86a2-62d3a2a81dfc.png)

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst  here are the steps to produce the issue:
-Add a camera with vendor and model values `"Unknown/Other"`, fill the details `(ip,snapshot url, http port)` test snapshot and save the camera.
-Go to `"Camera settings"` and see the details where you can see `"snapshot"` now go to `"Edit camera"` where you see as in screen shot, snapshot text field is empty, **it should be filled with snapshot value.**

**Comment by marcoherbst** [comment]
Good one, well spotted. Yes, that's an important one.
