### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by royalgarment** [evercam/evercam-android#244]
Hi,

Thank you for the awesome program, I have just downloaded it and it looks great but it seems to be having problems logging in. When I go into the create account screen, fill in the information and press create account, it just shows a progress for creating the account, when that is finished it returns a blank toast message, and is still on the account page. So I was not sure if my account had been created, I went to sign in but it returns that my user email doesn't exist. I have attached the part of the logcat from when I am creating the account. 

Please could you have a look and let me know what might be the problem?

Many thanks,
Ryan
[CantCreateAccount.txt](https://github.com/evercam/evercam-android/files/1169470/CantCreateAccount.txt)

**Comment by marcoherbst** [comment]
Hi Ryan,

Thanks for the compliments. 

Before looking into this any deeper, a note about the project and it's applicability. While this project is open source, AGPL, and you're welcome to work on it as you wish, our current direction is to steer it more and more in the direction of being a SaaS tool for construction companies. We're not really supporting it as a general purpose tool and nor is it being much used as such. What are you hoping to do with it? I might be able to steer you in a better direction. marco@evercam.io

M
