### ISSUE TITLE
release.properties file not found

### ISSUE THREAD

**Issue by Hannan321** [evercam/evercam-android#259]
This error occurs when i tried to download and run your project from github:
 ERROR: E:\Uni\FYP(FBGroup)\ProjectRP\GitHubProjects\ByEverCam2(ZulqarnainMustafa)\evercam-android-master\release.properties (The system cannot find the file specified)

**Comment by marcoherbst** [comment]
Sorry Hannan, we're not supporting this for outside developers. The first idea was to make an open source app for others, but now we've changed direction.
