### ISSUE TITLE
Multi camera view

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-android#51]

**Comment by liutingdu** [comment]
@GNUDimarik 

> If I got it right it should play several cameras simultaneously, if yes, we need to make separate pipeline for each one, it requires some changes in native stuff and I think it should be done before IOS version if you want to share this stuff between oses.

Thanks for letting me know this need to be done before share the GStreamer work with iOS.. We can work on this after zoom, but I'll need to think about how to change the app working flow for multiple views.

**Comment by GNUDimarik** [comment]
Test commited to branch multiview, please test
