### ISSUE TITLE
Add "Camera Offline" Notifications - Client Side

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-android#77]
Requirements on server side:
http://developer.android.com/google/gcm/server.html
1. Accept the app's registration request (with authentication)
2. Store user's device details(registration ID and so on)
3. When camera gets online/offline, send notification request to GCM server, along with the registration ID.

Requirements on client side: 
http://developer.android.com/google/gcm/client.html
1.  Enable GCM and retrieve valid registration ID
2.  Send registration ID to Evercam server
3.  Custom code to receive notification messages
4.  Save notification history??

Steps:
1. The Evercam server sends a message to GCM servers.
2. The GCM connection server enqueues and stores the message if the device is offline.
3. When the device is online, GCM connection server sends the message to the device.
4. The client app processes the message.
   Trello card for server side: https://trello.com/c/UtvHWNgh/1030-camera-offline-notifications-webhooks-server-side

**Comment by marcoherbst** [comment]
https://github.com/evercam/evercam-server/issues/578

**Comment by marcoherbst** [comment]
Closing
